// Generated by gencpp from file abot_vlm/LLMQuery.msg
// DO NOT EDIT!


#ifndef ABOT_VLM_MESSAGE_LLMQUERY_H
#define ABOT_VLM_MESSAGE_LLMQUERY_H

#include <ros/service_traits.h>


#include <abot_vlm/LLMQueryRequest.h>
#include <abot_vlm/LLMQueryResponse.h>


namespace abot_vlm
{

struct LLMQuery
{

typedef LLMQueryRequest Request;
typedef LLMQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LLMQuery
} // namespace abot_vlm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abot_vlm::LLMQuery > {
  static const char* value()
  {
    return "40ece397ad679f27203bff340007bd45";
  }

  static const char* value(const ::abot_vlm::LLMQuery&) { return value(); }
};

template<>
struct DataType< ::abot_vlm::LLMQuery > {
  static const char* value()
  {
    return "abot_vlm/LLMQuery";
  }

  static const char* value(const ::abot_vlm::LLMQuery&) { return value(); }
};


// service_traits::MD5Sum< ::abot_vlm::LLMQueryRequest> should match
// service_traits::MD5Sum< ::abot_vlm::LLMQuery >
template<>
struct MD5Sum< ::abot_vlm::LLMQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abot_vlm::LLMQuery >::value();
  }
  static const char* value(const ::abot_vlm::LLMQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abot_vlm::LLMQueryRequest> should match
// service_traits::DataType< ::abot_vlm::LLMQuery >
template<>
struct DataType< ::abot_vlm::LLMQueryRequest>
{
  static const char* value()
  {
    return DataType< ::abot_vlm::LLMQuery >::value();
  }
  static const char* value(const ::abot_vlm::LLMQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abot_vlm::LLMQueryResponse> should match
// service_traits::MD5Sum< ::abot_vlm::LLMQuery >
template<>
struct MD5Sum< ::abot_vlm::LLMQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abot_vlm::LLMQuery >::value();
  }
  static const char* value(const ::abot_vlm::LLMQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abot_vlm::LLMQueryResponse> should match
// service_traits::DataType< ::abot_vlm::LLMQuery >
template<>
struct DataType< ::abot_vlm::LLMQueryResponse>
{
  static const char* value()
  {
    return DataType< ::abot_vlm::LLMQuery >::value();
  }
  static const char* value(const ::abot_vlm::LLMQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABOT_VLM_MESSAGE_LLMQUERY_H
