// Generated by gencpp from file abot_vlm/LLMQueryResponse.msg
// DO NOT EDIT!


#ifndef ABOT_VLM_MESSAGE_LLMQUERYRESPONSE_H
#define ABOT_VLM_MESSAGE_LLMQUERYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abot_vlm
{
template <class ContainerAllocator>
struct LLMQueryResponse_
{
  typedef LLMQueryResponse_<ContainerAllocator> Type;

  LLMQueryResponse_()
    : result()  {
    }
  LLMQueryResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LLMQueryResponse_

typedef ::abot_vlm::LLMQueryResponse_<std::allocator<void> > LLMQueryResponse;

typedef boost::shared_ptr< ::abot_vlm::LLMQueryResponse > LLMQueryResponsePtr;
typedef boost::shared_ptr< ::abot_vlm::LLMQueryResponse const> LLMQueryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abot_vlm::LLMQueryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abot_vlm::LLMQueryResponse_<ContainerAllocator1> & lhs, const ::abot_vlm::LLMQueryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abot_vlm::LLMQueryResponse_<ContainerAllocator1> & lhs, const ::abot_vlm::LLMQueryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abot_vlm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::abot_vlm::LLMQueryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abot_vlm/LLMQueryResponse";
  }

  static const char* value(const ::abot_vlm::LLMQueryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::abot_vlm::LLMQueryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LLMQueryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abot_vlm::LLMQueryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abot_vlm::LLMQueryResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABOT_VLM_MESSAGE_LLMQUERYRESPONSE_H
