// Generated by gencpp from file abot_vlm/LLMQueryRequest.msg
// DO NOT EDIT!


#ifndef ABOT_VLM_MESSAGE_LLMQUERYREQUEST_H
#define ABOT_VLM_MESSAGE_LLMQUERYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abot_vlm
{
template <class ContainerAllocator>
struct LLMQueryRequest_
{
  typedef LLMQueryRequest_<ContainerAllocator> Type;

  LLMQueryRequest_()
    : query()  {
    }
  LLMQueryRequest_(const ContainerAllocator& _alloc)
    : query(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _query_type;
  _query_type query;





  typedef boost::shared_ptr< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LLMQueryRequest_

typedef ::abot_vlm::LLMQueryRequest_<std::allocator<void> > LLMQueryRequest;

typedef boost::shared_ptr< ::abot_vlm::LLMQueryRequest > LLMQueryRequestPtr;
typedef boost::shared_ptr< ::abot_vlm::LLMQueryRequest const> LLMQueryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abot_vlm::LLMQueryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abot_vlm::LLMQueryRequest_<ContainerAllocator1> & lhs, const ::abot_vlm::LLMQueryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.query == rhs.query;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abot_vlm::LLMQueryRequest_<ContainerAllocator1> & lhs, const ::abot_vlm::LLMQueryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abot_vlm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6490a46152f373285fe18f491ed93702";
  }

  static const char* value(const ::abot_vlm::LLMQueryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6490a46152f37328ULL;
  static const uint64_t static_value2 = 0x5fe18f491ed93702ULL;
};

template<class ContainerAllocator>
struct DataType< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abot_vlm/LLMQueryRequest";
  }

  static const char* value(const ::abot_vlm::LLMQueryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string query\n"
;
  }

  static const char* value(const ::abot_vlm::LLMQueryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LLMQueryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abot_vlm::LLMQueryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abot_vlm::LLMQueryRequest_<ContainerAllocator>& v)
  {
    s << indent << "query: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.query);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABOT_VLM_MESSAGE_LLMQUERYREQUEST_H
