// Generated by gencpp from file abot_vlm/VisionResultResponse.msg
// DO NOT EDIT!


#ifndef ABOT_VLM_MESSAGE_VISIONRESULTRESPONSE_H
#define ABOT_VLM_MESSAGE_VISIONRESULTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abot_vlm
{
template <class ContainerAllocator>
struct VisionResultResponse_
{
  typedef VisionResultResponse_<ContainerAllocator> Type;

  VisionResultResponse_()
    : success(false)  {
    }
  VisionResultResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::abot_vlm::VisionResultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abot_vlm::VisionResultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VisionResultResponse_

typedef ::abot_vlm::VisionResultResponse_<std::allocator<void> > VisionResultResponse;

typedef boost::shared_ptr< ::abot_vlm::VisionResultResponse > VisionResultResponsePtr;
typedef boost::shared_ptr< ::abot_vlm::VisionResultResponse const> VisionResultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abot_vlm::VisionResultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abot_vlm::VisionResultResponse_<ContainerAllocator1> & lhs, const ::abot_vlm::VisionResultResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abot_vlm::VisionResultResponse_<ContainerAllocator1> & lhs, const ::abot_vlm::VisionResultResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abot_vlm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abot_vlm::VisionResultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abot_vlm::VisionResultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abot_vlm::VisionResultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::abot_vlm::VisionResultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abot_vlm/VisionResultResponse";
  }

  static const char* value(const ::abot_vlm::VisionResultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::abot_vlm::VisionResultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisionResultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abot_vlm::VisionResultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abot_vlm::VisionResultResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABOT_VLM_MESSAGE_VISIONRESULTRESPONSE_H
