// Generated by gencpp from file abot_vlm/VisionResult.msg
// DO NOT EDIT!


#ifndef ABOT_VLM_MESSAGE_VISIONRESULT_H
#define ABOT_VLM_MESSAGE_VISIONRESULT_H

#include <ros/service_traits.h>


#include <abot_vlm/VisionResultRequest.h>
#include <abot_vlm/VisionResultResponse.h>


namespace abot_vlm
{

struct VisionResult
{

typedef VisionResultRequest Request;
typedef VisionResultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VisionResult
} // namespace abot_vlm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abot_vlm::VisionResult > {
  static const char* value()
  {
    return "5a308924dc8fc0f626a1724933b52b70";
  }

  static const char* value(const ::abot_vlm::VisionResult&) { return value(); }
};

template<>
struct DataType< ::abot_vlm::VisionResult > {
  static const char* value()
  {
    return "abot_vlm/VisionResult";
  }

  static const char* value(const ::abot_vlm::VisionResult&) { return value(); }
};


// service_traits::MD5Sum< ::abot_vlm::VisionResultRequest> should match
// service_traits::MD5Sum< ::abot_vlm::VisionResult >
template<>
struct MD5Sum< ::abot_vlm::VisionResultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abot_vlm::VisionResult >::value();
  }
  static const char* value(const ::abot_vlm::VisionResultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abot_vlm::VisionResultRequest> should match
// service_traits::DataType< ::abot_vlm::VisionResult >
template<>
struct DataType< ::abot_vlm::VisionResultRequest>
{
  static const char* value()
  {
    return DataType< ::abot_vlm::VisionResult >::value();
  }
  static const char* value(const ::abot_vlm::VisionResultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abot_vlm::VisionResultResponse> should match
// service_traits::MD5Sum< ::abot_vlm::VisionResult >
template<>
struct MD5Sum< ::abot_vlm::VisionResultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abot_vlm::VisionResult >::value();
  }
  static const char* value(const ::abot_vlm::VisionResultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abot_vlm::VisionResultResponse> should match
// service_traits::DataType< ::abot_vlm::VisionResult >
template<>
struct DataType< ::abot_vlm::VisionResultResponse>
{
  static const char* value()
  {
    return DataType< ::abot_vlm::VisionResult >::value();
  }
  static const char* value(const ::abot_vlm::VisionResultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABOT_VLM_MESSAGE_VISIONRESULT_H
