(cl:defpackage abot_vlm-srv
  (:use )
  (:export
   "LLMQUERY"
   "<LLMQUERY-REQUEST>"
   "LLMQUERY-REQUEST"
   "<LLMQUERY-RESPONSE>"
   "LLMQUERY-RESPONSE"
   "VISIONRESULT"
   "<VISIONRESULT-REQUEST>"
   "VISIONRESULT-REQUEST"
   "<VISIONRESULT-RESPONSE>"
   "VISIONRESULT-RESPONSE"
  ))

