// Generated by gencpp from file TTS_audio/TTS.msg
// DO NOT EDIT!


#ifndef TTS_AUDIO_MESSAGE_TTS_H
#define TTS_AUDIO_MESSAGE_TTS_H

#include <ros/service_traits.h>


#include <TTS_audio/TTSRequest.h>
#include <TTS_audio/TTSResponse.h>


namespace TTS_audio
{

struct TTS
{

typedef TTSRequest Request;
typedef TTSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TTS
} // namespace TTS_audio


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::TTS_audio::TTS > {
  static const char* value()
  {
    return "4027c3e5e88791dcb539699a421751c8";
  }

  static const char* value(const ::TTS_audio::TTS&) { return value(); }
};

template<>
struct DataType< ::TTS_audio::TTS > {
  static const char* value()
  {
    return "TTS_audio/TTS";
  }

  static const char* value(const ::TTS_audio::TTS&) { return value(); }
};


// service_traits::MD5Sum< ::TTS_audio::TTSRequest> should match
// service_traits::MD5Sum< ::TTS_audio::TTS >
template<>
struct MD5Sum< ::TTS_audio::TTSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::TTS_audio::TTS >::value();
  }
  static const char* value(const ::TTS_audio::TTSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::TTS_audio::TTSRequest> should match
// service_traits::DataType< ::TTS_audio::TTS >
template<>
struct DataType< ::TTS_audio::TTSRequest>
{
  static const char* value()
  {
    return DataType< ::TTS_audio::TTS >::value();
  }
  static const char* value(const ::TTS_audio::TTSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::TTS_audio::TTSResponse> should match
// service_traits::MD5Sum< ::TTS_audio::TTS >
template<>
struct MD5Sum< ::TTS_audio::TTSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::TTS_audio::TTS >::value();
  }
  static const char* value(const ::TTS_audio::TTSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::TTS_audio::TTSResponse> should match
// service_traits::DataType< ::TTS_audio::TTS >
template<>
struct DataType< ::TTS_audio::TTSResponse>
{
  static const char* value()
  {
    return DataType< ::TTS_audio::TTS >::value();
  }
  static const char* value(const ::TTS_audio::TTSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TTS_AUDIO_MESSAGE_TTS_H
