// Generated by gencpp from file TTS_audio/TTSRequest.msg
// DO NOT EDIT!


#ifndef TTS_AUDIO_MESSAGE_TTSREQUEST_H
#define TTS_AUDIO_MESSAGE_TTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TTS_audio
{
template <class ContainerAllocator>
struct TTSRequest_
{
  typedef TTSRequest_<ContainerAllocator> Type;

  TTSRequest_()
    : text()  {
    }
  TTSRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::TTS_audio::TTSRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TTS_audio::TTSRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TTSRequest_

typedef ::TTS_audio::TTSRequest_<std::allocator<void> > TTSRequest;

typedef boost::shared_ptr< ::TTS_audio::TTSRequest > TTSRequestPtr;
typedef boost::shared_ptr< ::TTS_audio::TTSRequest const> TTSRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TTS_audio::TTSRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TTS_audio::TTSRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::TTS_audio::TTSRequest_<ContainerAllocator1> & lhs, const ::TTS_audio::TTSRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::TTS_audio::TTSRequest_<ContainerAllocator1> & lhs, const ::TTS_audio::TTSRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace TTS_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::TTSRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::TTSRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::TTSRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::TTSRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::TTSRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::TTSRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TTS_audio::TTSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::TTS_audio::TTSRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::TTS_audio::TTSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TTS_audio/TTSRequest";
  }

  static const char* value(const ::TTS_audio::TTSRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TTS_audio::TTSRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
;
  }

  static const char* value(const ::TTS_audio::TTSRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TTS_audio::TTSRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TTSRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TTS_audio::TTSRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TTS_audio::TTSRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTS_AUDIO_MESSAGE_TTSREQUEST_H
