// Generated by gencpp from file TTS_audio/TTSResponse.msg
// DO NOT EDIT!


#ifndef TTS_AUDIO_MESSAGE_TTSRESPONSE_H
#define TTS_AUDIO_MESSAGE_TTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace TTS_audio
{
template <class ContainerAllocator>
struct TTSResponse_
{
  typedef TTSResponse_<ContainerAllocator> Type;

  TTSResponse_()
    : audio_file_path()  {
    }
  TTSResponse_(const ContainerAllocator& _alloc)
    : audio_file_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _audio_file_path_type;
  _audio_file_path_type audio_file_path;





  typedef boost::shared_ptr< ::TTS_audio::TTSResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TTS_audio::TTSResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TTSResponse_

typedef ::TTS_audio::TTSResponse_<std::allocator<void> > TTSResponse;

typedef boost::shared_ptr< ::TTS_audio::TTSResponse > TTSResponsePtr;
typedef boost::shared_ptr< ::TTS_audio::TTSResponse const> TTSResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::TTS_audio::TTSResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::TTS_audio::TTSResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::TTS_audio::TTSResponse_<ContainerAllocator1> & lhs, const ::TTS_audio::TTSResponse_<ContainerAllocator2> & rhs)
{
  return lhs.audio_file_path == rhs.audio_file_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::TTS_audio::TTSResponse_<ContainerAllocator1> & lhs, const ::TTS_audio::TTSResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace TTS_audio

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::TTSResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::TTS_audio::TTSResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::TTSResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::TTS_audio::TTSResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::TTSResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::TTS_audio::TTSResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::TTS_audio::TTSResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d71d2815b94c8285786e11e368ad5ac";
  }

  static const char* value(const ::TTS_audio::TTSResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d71d2815b94c828ULL;
  static const uint64_t static_value2 = 0x5786e11e368ad5acULL;
};

template<class ContainerAllocator>
struct DataType< ::TTS_audio::TTSResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TTS_audio/TTSResponse";
  }

  static const char* value(const ::TTS_audio::TTSResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::TTS_audio::TTSResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string audio_file_path\n"
"\n"
;
  }

  static const char* value(const ::TTS_audio::TTSResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::TTS_audio::TTSResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.audio_file_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TTSResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TTS_audio::TTSResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::TTS_audio::TTSResponse_<ContainerAllocator>& v)
  {
    s << indent << "audio_file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.audio_file_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTS_AUDIO_MESSAGE_TTSRESPONSE_H
